### ISSUE TITLE
Create separate branch for different version of android studio

### ISSUE THREAD

**Issue by vharron** [googlesamples/android-ndk#105]
Not all Android Studio users are on the latest version.  Currently, we have one samples repo shared across multiple versions of Android Studio.  I'm concerned that samples updated to use the latest Android Studio version won't work in older Android Studio releases and old samples with deprecated functionality will fail to work in later Android Studio versions.

**Comment by proppy** [comment]
Android Studio 1.3+ is recommended (in the README) because of C++ highlighting and native debugging support.

All samples are depending on a specific version of the gradle plugin to build (the `gradle-experimental` one that support the native build system), the NDK toolchain and the NDK APIs.
We update them all in sync when new versions comes out and all the CI build are green: see #101.

I'm not sure how a new Android Studio version could break the sample, to you have something specific in mind?

**Comment by proppy** [comment]
This is blocked by android studio supporting importing sample from branches.

**Comment by ggfan** [comment]
closing this one for now: just about merging everything into one branch ( cmake + ndkbuid + experimental) to share the native code, not sure will ever move to this item.
