### ISSUE TITLE
native-media sample doesn't work out of the box

### ISSUE THREAD

**Issue by zacpez** [googlesamples/android-ndk#117]
I was curious to explore video decoding and rendering in the native-media sample, but it doesn't seem to work correctly at run time, the video simply doesn't appear on screen. It compiles with Android Studio 1.4 successfully, transfers to Galaxy S6, and it opens and runs. However, when pressing Play/Pause Java MediaPlayer button it crashes; and when pressing the Play/Pause Native MediaPlayer it just doesn't do anything. Each of the surfaces remains black. I have tried to figure out some solutions to no avail.

**Comment by proppy** [comment]
Related #55 #41 #40

**Comment by Whiteseeker** [comment]
Should we put the video to be decoded in the asset folder instead and use the [asset api](http://developer.android.com/ndk/reference/group___asset.html) to read it ?

It would let people compile, deploy and it would work *out of the box*.

I could do that if you want (Assign it to me or just tell me)

**Comment by proppy** [comment]
@Whiteseeker Yes, I suggested that to @ggfan before. I think that's a good idea.

**Comment by ggfan** [comment]
this one is fixed with 
  https://github.com/googlesamples/android-ndk/pull/182
be cautious though, I disabled the native_player side:  something wrong with it I could not see it working before this code change and after this code change.  some more work need to be done and will do it

the issues specific to this bug are fixed, we are playing from asset so clips will always there. apk will be big and pretty big since we are build one apk for all... Will use this sample and native-codec as example for split spk sample later. 

The clip is updated too, the old one has some CRC problem.

check it out and re-open if there is problem for it, thanks
