### ISSUE TITLE
Create examples that leverage apply plugin: 'com.android.model.native'

### ISSUE THREAD

**Issue by 2bitProgammer** [googlesamples/android-ndk#152]
According to the [documentation](http://tools.android.com/tech-docs/new-build-system/gradle-experimental) Section **Standalone NDK Plugin**, we should be able to build native code that doesn't require an app at all.  There are no examples of `apply plugin: 'com.android.model.native'` nor `apply plugin: 'com.android.model.library'` in the samples.

**Comment by proppy** [comment]
#116 is doing some of this, I'd love your comment on it.

**Comment by ggfan** [comment]
hello-libs provided a sample of com.android.model.native; 
nativeactivity module uses com.android.model.library [ static lib ], which is used in a few samples(native-activity/teapot/MoreTeapot/EndlessTunnel). It is partially working in that only gcc could build, with clang, need some hacking: copying ar from gcc too into clang toolchain directory. So you would end up in a blend of  gcc-for-lib, clang-for-app; it works for native-activity so far. When the fix is in for clang, will update it accordingly

close this for now, please re-open if you feel we need investigate more

**Comment by IgorGanapolsky** [comment]
@ggfan So Gradle-Experimental is going away in favor of CMake going forward?

**Comment by ggfan** [comment]
Three technologies are moving forward from what I see:  cmake/ndk-build/gradle-experimental.  kind of do-not-know answer, sorry

**Comment by IgorGanapolsky** [comment]
@ggfan Is it possible to figure out which approach is more favorable?  I mean we are currently relying on **gradle-experimental** for NDK in my company.  However, how can we know whether there is a necessity to switch to **CMake**?

**Comment by ggfan** [comment]
very valid question, hope have an answer soon ...
