### ISSUE TITLE
Clang toolchain does not work from Android Studio

### ISSUE THREAD

**Issue by psiha** [googlesamples/android-ndk#167]
Specifying stl = 'c++_static' and toolchain = 'clang' with:
- Android Studio 1.5.1 or 2.0 or 2.1 beta
- NDK 10e or 11c
- Gradle 2.10
- plugin 0.6.0 or 0.7.0 beta1
results in bogus errors (mostly about incomplete -x parameters passed to the compiler when you try to build the project) both in my 'private' projects and in freshly imported 'googlesamples'...
Using Clang+libc++ through the 'old fashioned' NDK_BUILD works OK...

("interesting" considering that GCC is deprecated and Clang should be the default...yet it not only isn't the default, it does not work)...

**Comment by ggfan** [comment]
maybe you are on windows?

there is a bug when android studio/gradle generating clang compile options, so clang on windows build is busted [ for a long while and still is]. Good thing is that this is brought up as urgent thing, it will be fixed soon and those samples should be updated accordingly then

On Mac build, clang seems to be ok to me, but could not enable -Wall -Werror, because clang throws warning about "inline"; I tried to use -Wall -Werror with gcc, correct all errors and then change back to clang AND remove -Wall -Werror. 

hope this helps

**Comment by ggfan** [comment]
clang is re-enabled with 0.7.0-rc1 ( will update to 0.7.0 soon ); so this is ok now.  I think we are more leaning toward gnustl_static/shared now, and recommending thorough validation when using c++_static/shared.  close this one, reopen if you still see the problem.
