### ISSUE TITLE
so file generation in Hello-libs sample

### ISSUE THREAD

**Issue by ntimesc** [googlesamples/android-ndk#220]
i tried running `Hello-libs` sample from google samples successfully but what i wondered the most is from where *.so files are generated in Hello-libs ?

does android studio generates that or do we need to manually generate it for all platform or is there any other way to do so ? even i dont see any *.mk file in a folder from which one could generate *.so files.

**Comment by ggfan** [comment]
yeah,  the libs are created by THIS sample, copied the so files and header files into a common directory  AND also used by this sample FROM the common directory.  for that purpose, 
1) for creating libs with android studio, please look at the gmath/build.gradle or gperf/build.gradle
2) the scripts copying out the so and header file is at the bottom of the above 2 scripts
3) for using the shared libs, the scripts is inside app/src/main/build.gradle
        there are some comments in app/src/main/build.gradle about how to use static lib [just do not put static lib inside jniLibs {} because static lib no need to be copied to target [I probably should add it into that section]

hello-libs/README.md has short bullets about the above points.

**Comment by ntimesc** [comment]
so based on that i am trying to add POCO library and my structure looks as follows


![2](https://cloud.githubusercontent.com/assets/5063898/15682764/d50e654e-277c-11e6-8fbb-c4d7ef3893ea.png)

as you can see i have created a moduleand made following changes in gradle 


![1](https://cloud.githubusercontent.com/assets/5063898/15682796/f79b5b62-277c-11e6-8d57-46738f79c588.png)

but after i build the project i dont see any so files in following path 

E:\ndk\NdkProto\poco\build\intermediates\binaries\debug\lib

i can view following folders but all are empty

![3](https://cloud.githubusercontent.com/assets/5063898/15682912/6cb53080-277d-11e6-8770-533861a4b267.png)

**Comment by ggfan** [comment]
right hand side android studio, you see "Gradle" on the edge of IDE, expand it; Poco should be there.
expand it,  try with: :poco -> Tasks -> assemble, click on it to force a build, and check your result.

in the sample, this is forced via script:
   app/build.gradle  at the end of the file, tasks.whenTaskAdded {}
   gmath/build.gradle task(distributeLib, type : Copy) {
      dependsOn assemble  <== this force a build for libs
it is a hack in the sample anyway, so it is just to simulate action of "generate lib, distribute to someone, someone use the lib"

**Comment by ntimesc** [comment]
i have now added following in build.gradle (app)

```
tasks.whenTaskAdded { task ->
    if (task.name.contains('compile')) {
        task.dependsOn ':poco:distributeLib'
    }
}
```


and following lines in build.gradle ( poco)

```
task(distributeLib, type : Copy) {
    // trigger build library
    dependsOn assemble
    into '../distribution/poco/'
    from('src/main/jni/') {
        into 'include/'
    }
    from('build/outputs/native/release/lib') {
        into 'lib/'
    }
}
```

and tried to  run assemble task too, but still my folders are blank


![4](https://cloud.githubusercontent.com/assets/5063898/15685124/f49098e6-2787-11e6-8a61-ce52f38484aa.png)

**Comment by ggfan** [comment]
maybe we try to work on to make it manually to work first, forget about the scripts now.
1) poco --> tasks --> build --> clean
2) rm -fr poco/build [terminal]
3) poco --> tasks --> build --> assemble
4) cd poco/build/outputs/...   check what have there under debug and release

how could we chat online on github or via gmail? that way it is faster

**Comment by ntimesc** [comment]
nihar.b.bhatt@gmail.com is my id , lets chat on gmail

**Comment by ggfan** [comment]
managed with ndk-build to build libs after the chat:  looks like there are four libs: PocoFoundation.a  libPocoFoundation.a libPocoJSON.a, libPocoNet.a  and libPocoUtils.a by following your pointed out link 
   1) https://github.com/aksalj/Poco
   2) make own toolchain and copy it into .../Poco/Platform/Android/toolchain
   3) add made toolchain into path
   4) ./build.sh 1.7.3 6.1 Android CLEAN

once you get those on your end, you could do something similar to hello-libs -- app/src/main/build.gradle, refer to comment on top of gperf lib for static lib configuration.  you will need to do it for each static libs in your case.  This should get the work done and you do not have to build it inside your app anymore -- it is quick way.

Android studio does not support directly building out static lib; there is an indirect way, but since you already have ndk-build for your libs, may not worth the efforts to build static lib with another way.  if you are just interested in to use the poco in your own project, you could follow the teapot sample, look at the way how nativeactivity is used, that would get the work done. From my understanding, I think this would fit more into your usage, but does need to dig more into source package to see where are the sources and includes and configure your module accordingly

So 2 ways to get it done, hope at least one could please you more  :-)

thank you for bring it up

**Comment by ggfan** [comment]
@ntimesc, are you able to get over it now?  kindly update it when you get change. thanks

**Comment by ggfan** [comment]
AS 2.2.0 is released, please re-open the bug if the problem is still there  thanks
