### ISSUE TITLE
how quoted c++ source code in android studio in experimental - plugin- 0.7.2

### ISSUE THREAD

**Issue by agoodcoolman** [googlesamples/android-ndk#257]
I want to quote an open source library (transcode), but I can't find any stiatic library (.so) or dynamic library(.a)  in the webside.

I had copied trancscode source code in ndk-dir/source files.
[my project site](https://github.com/agoodcoolman/android_studio_ndk)

I had saw hello-libs,but i couldn't understand it.

**Comment by ggfan** [comment]
in this repo, there are 3 branches targeting for 3 different native code build for android OS with android studio, scroll down this page, you see that is says 2 :-)
  https://github.com/googlesamples/android-ndk
the hidden one is master-ndkbuild ( I only have limited time to support ndkbuild )

so if you do not care which build system it is, start with android studio's cmake support, which is in  master-cmake branch, see if hello-libs demo could help you.

you probably will not find too many open source projects releasing binary for android due to the stl type, toolchain version, and ABIs. If I were doing it, I would:
- create cmake files for the transcode project in a separate directory ( not directly inside their source code ) to build static lib(s) for android
- create android app with some native code, to be called by app's java code
- use app's native code to call into transcode's lib, so call stays in native domain.

In this way you could update the transcode source code independently, without any merging with your code at all.

**Comment by ggfan** [comment]
are you able to proceed now? thanks

**Comment by agoodcoolman** [comment]
use the ndkbuild  brand ,it's work for me.
