### ISSUE TITLE
Unable to include .h files in externalNativeBuild

### ISSUE THREAD

**Issue by lkmoe** [googlesamples/android-ndk#258]
Hi!

I would like to port one of my existing jni projects (which was using an approach like [this](https://github.com/googlesamples/tango-examples-c/blob/master/cpp_motion_tracking_example/app/build.gradle#L25)) to externalNativeBuild to make use of the C++ syntax highlighting and code completion provided.
I tried to _„Link C++ Project with Gradle“_ in Android Studio 2.2 Preview 3 to reuse and link to my existing Android.mk file which includes aswell static and shared libraries and works fine with my previous approach. 
My Problem: When I try to build the project/apk, _app:externalNativeBuildDebug_ cannot find my included header files (.h) located in my „include“ directories and linked in my Android.mk using `LOCAL_C_INCLUDES` and `LOCAL_EXPORT_C_INCLUDES`. (I receive: _Information: (Unknown) In file included_ and _Error: extlib/file.h: No such file or directory_)

Any ideas what I might be missing? Or am I on the wrong track?

Any help would be appreciated and many thanks in advance.

**Comment by ggfan** [comment]
yes, this one is kind of out of my guess:  your project is not using the new ndk support built into studio. Basically you are compiling your ndk code with a separate task which studio has not knowledge of it. Taking a big guess: 

- build with ndk-build command line, make sure it still buildable; then put your *.so file into the jniLibs directory so it is packed into apk. If this works, then you know it is not far from to get it working with your customized building way with studio.
- inside the studio, only build task "ndkBuild" [ from right hand side of studio, or on terminal], and fix issues happening there. your command line options should be same as the one you use on terminal ( above step ). make sure you have your *.so files into jniLibs folder
- then you try to build all inside studio and project/apk

All you are doing does require anything from studio features because you are doing the things by yourself. 

If I could recommend, you could try to use the new native feature within studio as 
` externalNativeBuild {
        ndkBuild {
            path 'src/main/cpp/Android.mk'
        }`

it does the things you want to do automatically. There is an option for pointing to your Application.mk as:
`defaultConfig {
     externalNativeBuild {
         ndkBuild {
          "NDK_APPLICATION_MK:=src/main/cpp/Application.mk"
         }
     }
  }
`
this way might save you lot of hacking on gradle customized build task.

**Comment by ggfan** [comment]
maybe I was on the wrong guess: you are already using the ndkbuild integration in new Android Studio already?

**Comment by lkmoe** [comment]
yes, i was using the ndkbuild integration already (as described [here](http://tools.android.com/tech-docs/external-c-builds) and with Android Studio 2.2 Preview 3 and gradle:2.2.0-alpha4 build tools). It couldn't find my header files in the "include" folders when building external libs for some reason (even though I linked them in my Android.mk) and I still couldn't manage to fix it. Therefore I wrote CMakeLists.txt files and „Linked C++ Project with Gradle“ using these CMake files. This works fine so far!!

**Comment by ggfan** [comment]
thanks! cmake has more flexibility, I would go for it for the new project.  I will port 2 libs into ndkbuild, at that time, I will be able to see the problem.

**Comment by ggfan** [comment]
hello-libs is ported into master-ndkbuild branch, works for me on Mac X, you may check it out.  Closing this one for now, feel free to re-open it, thanks!

**Comment by viperpiper** [comment]
I know it is a bit late for the original poster, but for anyone else interested, a solution to the original problem is to prefix the paths of the entries in LOCAL_C_INCLUDES with:

`$(LOCAL_PATH)//`

So if the original entry was:

`LOCAL_C_INCLUDES := externals/audioAnalyser/src`

then change it to:

`LOCAL_C_INCLUDES := $(LOCAL_PATH)//externals/audioAnalyser/src`
