### ISSUE TITLE
gmath cannot build

### ISSUE THREAD

**Issue by zhaoboqiang** [googlesamples/android-ndk#288]
Both macosx and windows 10 occurs.

1.remove distribution directory;
2../gradlew build;

Failed:
Expected output file at libgmath.a for target gmath but there was none

**Comment by ggfan** [comment]
yeah, the task to generate lib is distributeLib (open lib's build.gradle, you will find it at the bottom):
rm -fr distribution
gradlew gmath:distributeLib gperf:distributeLib

then you could check the result.  The purpose for this project is to demo how to import a lib from outside; less focus on how the lib is generated. If a big project wants to be modularized (but NOT distributing lib to other projects), it could use 
- 'com.android.library' for static ones
- 'com.android.model.native' for pure shared libs (gperf and gmath is using this one)

**Comment by ggfan** [comment]
Oops, keeps on hit wrong button: github should swap the 2 buttons

**Comment by ggfan** [comment]
like to close the issue if it is ok:  the key idea for this hello-libs sample is for how to import external lib. please avoid trying to generate lib and also use it in ONE build:  the parallel building is going to cause trouble -- there is no dependency inside app's build.gradle ( again we do not want any dependency there because we assume the lib is coming from external world)
