### ISSUE TITLE
I was trying to call a function from cpp, without using cmake, can you please help

### ISSUE THREAD

**Issue by Anvesh46** [googlesamples/android-ndk#300]

**Comment by ggfan** [comment]
the code is still uploading for 3 hours, might be something wrong?

**Comment by Anvesh46** [comment]
[JNITest.zip](https://github.com/googlesamples/android-ndk/files/488759/JNITest.zip)

**Comment by ggfan** [comment]
the difference is the FindClass(), the change "." with "/" for class name.  other changes are minor.     https://gist.github.com/ggfan/6ccef9ac609d400e36504134ce0257a7

get GlobalReference portion is commented out in this case since it is still valid; creating a globalReference before using it would be safer

**Comment by Anvesh46** [comment]
thanks it is working
