### ISSUE TITLE
About Teapot Sample

### ISSUE THREAD

**Issue by NativeCodeSamples** [googlesamples/android-ndk#314]
Can you provide a Teapot sample that we can learn below things.
1. How to use textures with 3D Teapot model with a use of "bitmap" and ".tga" file ? 

i mean that how to bind textures with a use of .bmp  or .tga files to 3D Model via NDK code.

**Comment by ggfan** [comment]
adding @hak

**Comment by ggfan** [comment]
less than 2 years, got chance to address this one  with https://github.com/googlesamples/android-ndk/pull/555

Loading file from assets probably is the only one specific to Android; this one avoids the reading from disk because I like to avoid to get too much Java code into it ( Run time permission is only available from Java ).
