### ISSUE TITLE
Teapot Sample

### ISSUE THREAD

**Issue by NativeCodeSamples** [googlesamples/android-ndk#316]
While I use 'glVertexPointer', 'glNormalPointer', and 'glTexCoordPointer' Android studio showing error in Classic-Teapot Sample :

undefined reference to 'glVertexPointer'
undefined reference to 'glNormalPointer'
undefined reference to 'glTexCoordPointer' 

my code is below.

glTexCoordPointer( 2, GL_FLOAT, 0, teapotTexCoords);
  glVertexPointer(3, GL_FLOAT, 0, teapotPositions);
  glNormalPointer(GL_FLOAT, 0, teapotNormals);

Can you help me ?

**Comment by ggfan** [comment]
Sorry for the delay. These are open GL 1.x functions for fixed function pipelines (no shaders).  Teapot samples are dynamically detecting GL version 3.0 availability
- if underlying Android OS supports OpenGL ES 3.0, use it
- otherwise use version 2.0
refer to [InitGLES()](https://github.com/googlesamples/android-ndk/blob/master/teapots/common/ndk_helper/GLContext.cpp#L50)

Teapot samples will not compile with OpenGL 1.x.

But your application could use OpenGL 1.x with:

1. include the right header files
```java
#include <EGL/egl.h>
#include <GLES/gl.h>
```
all headers are inside `android-ndk-r16/sysroot/usr/include/GLES`
2. link with the right lib, inside your own CMakeLists.txt, link with lib GLESV1_CM
```java
target_link_libraries(TeapotNativeActivity
    EGL
    GLESv1_CM
    android
    log
   ... many other of your libs)
```

**Comment by ggfan** [comment]
forgot one thing: for this type of questions, please filed it to StackOverflow, there will be plenty of OpenGL experts to help right away. Apologize for the delay: there are constantly many things going on at the same time, sometimes maintaining sometimes get lowered on priority.

**Comment by NativeCodeSamples** [comment]
Don't worry... it's all right
