### ISSUE TITLE
Q: CMake build output on AS + CMake

### ISSUE THREAD

**Issue by jnuevo** [googlesamples/android-ndk#341]
When changing the build options in the CMakeLists.txt or the build.gradle, it'd be very useful to see the verbose build commands. With the Makefile generation on a command line build, setting `set(CMAKE_VERBOSE_MAKEFILE ON)` in the CMakeLists.txt does the trick.

Is that possible on Android Studio + CMake? Where is the build output being logged to?

**Comment by ggfan** [comment]
the output would be all inside $proj/$app/.enxternalNativeBuild folder. early stage samples having this in cmakelists.txt files, then cleaned-out later on

**Comment by ggfan** [comment]
actually I did not find it goes to anywhere at all:  tried to build with and without it for teapot, no difference on command line and log file.  Since this flag is for make ( Makefile ) tools, my guess is that it has no effect:  AS + CMake uses ninja to build directly, not the make utility.  Yeah, from my investigation -- no, does not have effect. if I get more info, I will update this one ( or let us know if you find more different info :-) ).

**Comment by beeender** [comment]
This is quite an annoy problem. When cmake running from AS or command line, all outputs are silenced. Even all the compile warnings can only be shown when there is a build error happens. Wouldn't it be possible to redirect cmake outputs to gradle?

**Comment by ggfan** [comment]
yeah, passed on the info to the team, hope for the best. thank you for bringing it up

**Comment by giladreich** [comment]
While looking into this, I found this issue through google search. The way it's done is by adding verbose mode property to `gradle.properties` file:
```
# Enable verbose output to see cmake and ninja logs during build for native output:
# https://developer.android.com/studio/releases/gradle-plugin#native-build-output
android.native.buildOutput=verbose
``` 

Woho...we got some logs! But wait, it's not as verbose as I wanted. I want to see the compiler flags passed to each compilation object etc. So I wen't to the `CMakeLists.txt` file and enabled `CMAKE_VERBOSE_MAKEFILE` property:
```cmake
set(CMAKE_VERBOSE_MAKEFILE TRUE CACHE BOOL "" FORCE)
```
Note the `FORCE` flag, otherwise this won't work.

After that step, I still don't see the verbose logs I wanted to see from Ninja. So the hacky workaround is to trick the executable to always pass the `-v` flag, but how? Android Studio's CMake bundles Ninja executable as well, so at least on macOS that's how I do it:
```
mv $HOME/Library/Android/sdk/cmake/3.18.1/bin/{ninja,ninja_bak}
vim $HOME/Library/Android/sdk/cmake/3.18.1/bin/ninja
```
and then paste the following content:
```bash
#!/bin/bash
$HOME/Library/Android/sdk/cmake/3.18.1/bin/ninja_bak "${@}" -v
```
finally give the script permissions to execute:
```sh
chmod +x $HOME/Library/Android/sdk/cmake/3.18.1/bin/ninja
```
Verbose logs should now show-up.
