### ISSUE TITLE
Create a sample to demonstrate the native camera API

### ISSUE THREAD

**Issue by qchong** [googlesamples/android-ndk#349]
@ggfan @hak 

Can you please provide a sample to demonstrate the [native camera API](https://developer.android.com/ndk/reference/group___camera.html) (added for API level 24)?

Add Items from https://github.com/googlesamples/android-ndk/issues/360

- delivers photos from the buffer as captures priview and take a photo. with bitmap conversion

**Comment by ggfan** [comment]
get one passthrough working ( preview ), will check in soon ( after cleaning up ).  Could you think about the list of the features you want to see inside the sample?

**Comment by skanti** [comment]
@ggfan can you also tell something about controlling the camera frame rate? It would be nice to fetch with 60 FPS (or higher if possible).

**Comment by gitunit** [comment]
@ggfan how is the progress? would love working with this "new" api

**Comment by ggfan** [comment]
Oops, I have not tracking the bug here and missed all of your comment  :-(.  ( just updated the sample called it camera basic, and merged into this branch)

the basic portion also merged into the main branch just a moment ago:
  it does preview and take photos, purely on NDK side ( no java involvement other than get-run-time-permission), the taking photo portion is auto, the preview session is manual just to show how to get the control going. The doc in camera header files missed the structure for individual tags, which could be find inside AOSP camera source code directory ( not inside NDK's headers ). That is main gotcha.

will look at the textureView side.  thanks

**Comment by ggfan** [comment]
@skanti some frame rate info from here:
 https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#SENSOR_FRAME_DURATION

The camera tags are same for Java and NDK side, the description would apply. Hope this helps; you may also file an issue on Stack Overflow. We could address it there. It is interesting one, the exposure time definitely affect frame rate.
