### ISSUE TITLE
Could you please put an example of ndk camera

### ISSUE THREAD

**Issue by saulex** [googlesamples/android-ndk#360]
Could you please put an example of ndk camera. A simple example that delivers photos from the buffer as captures priview and take a photo. With bitmap conversion. The documentation of the implementation of the library is very scarce. Thank you ver much

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-ndk/pull/356, there is another bug for this thing; we are looking at the interface to see how to get something.  Right now it is WIP, just having preview there, planning to add capture into texture into OGL to display ( for your purpose, you could look at the image-read app in that sample, but it does not take photo yet).

we like to merge your issue into this one: https://github.com/googlesamples/android-ndk/issues/349
please put your requirements there ( will add the "taking photos" there ), also we are happy to hear what content you are expecting to see in the document. Right now the only NDK documentation is the reference which is direct lifted from header files; and Java side doc at https://developer.android.com/reference/android/hardware/camera2/package-summary.html.  Once you enter your desired lists, we could shot for them.

anyhow, let's merge to this to https://github.com/googlesamples/android-ndk/pull/356, and please add what you like to see there;  feel free to re-open this one if you think otherwise.  thanks
