### ISSUE TITLE
android-ndk-master-ndkbuild project doesn't work when its downloaded to a folder with space.

### ISSUE THREAD

**Issue by smudunuri123** [googlesamples/android-ndk#361]
Hi, 

1.Create a folder with "Sample Application"
2. Download 
https://github.com/googlesamples/android-ndk/tree/master-ndkbuild into the folder
3. Open the Hello JNI or Teapots project in the Studio

Expected: Soulld compile without any errors. 
Actual; Error:(48, 0) C:\src\Sample: No such file or directory
<a href="openFile:C:\Users\smudunuri\AppData\Local\Android\Sdk\ndk-bundle\build\core\add-application.mk">Open File</a>

If you create a folder without space, everything works well.

**Comment by ggfan** [comment]
sorry for pretty being slow on this repo.  this might be expected:
https://android.googlesource.com/platform/ndk/+/2d77f5a05f60029c981f299b222cfe28db18ccf7/build/core/build-local.mk

lines around 34 -- 38
```java
ifneq ($(words $(NDK_ROOT)),1)
    $(info Android NDK: You NDK installation path contains spaces.)
    $(info Android NDK: Please re-install to a different location to fix the issue !)
    $(error Aborting.)
endif
```
the file is in your local installed ndk package @ build/core/build-local.mk

Will bring it up when getting a chance, probably not expecting too quick response since there are so many other things going on with NDK in next releases ( like unified headers etc ).
