### ISSUE TITLE
hello-libs example in master-cmake may has error

### ISSUE THREAD

**Issue by wudijimao** [googlesamples/android-ndk#371]
I see no "gen-lib" module include in settings.gradle. And it can't really gen these libs, but only use it.
And the gen-lib module seems can't gen gmath.a.  I want to know that, how can I gen static libs with cmake. Thank you very much!😭

**Comment by wudijimao** [comment]
Thank you so much. I got it. But I think the example should content this for the beginner?

**Comment by ggfan** [comment]
yeah, good point. probably add the link to the gradle files or cmakelists.txt.  the lib should still be able to be generated once removing the commented out lines in settings.gradle/build.gradle ( I used "build apk" ).  if does not work for you, probably it is due to synchronization related things (gradle and cmake build does not wait on each other -- on cmake side itself, it does NOT aware lib's native should be built before it starts, hence sometimes error.  i.e, app modules needs gmath.a, but gmath is still in building process -- not finished yet.  Command line should not have this problem  -- I am guessing ).  Will think about it after fighting with camera/audio/others is over: add one in-app lib might be good approach.  will close this one for now but definitely think about it later.  thanks
