### ISSUE TITLE
Why the Endless Tunnel sample has the dependency constraint-layout 

### ISSUE THREAD

**Issue by Zingam** [googlesamples/android-ndk#379]
Some of the samples (Native Activity) seem to have dependencies that should be related to Java apps. Why does for example the "Endless Tunnel" sample have these dependencies:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.1'
}
```

**Comment by ggfan** [comment]
True, this probably due to the sample project template was used  during the porting process.  This project does not have any Java source code( yet:  should add some to handle run-time permission for writing disk because it does try to write out files in certain scenarios, just not time for it )

If you have chance, please add a patch. Otherwise it will be removed in next checkin here

**Comment by ggfan** [comment]
fixing it with: https://github.com/googlesamples/android-ndk/pull/387
