### ISSUE TITLE
Fetching images of AIMAGE_FORMAT_JPEG fails

### ISSUE THREAD

**Issue by skanti** [googlesamples/android-ndk#384]
When fetching images I encounter something strange:

``` c++
ASSERT(AIMAGE_FORMAT_JPEG == src_format, "Failed to get format");
AImage_getHeight(image, &height);
AImage_getWidth(image, &width);
AImage_getPlaneData(image, 0, &pixel, &y_len);

AImage_getPlaneRowStride(image, 0, &stride); // <-- NOT SUPPORTED FOR JPEG
AImage_getPlanePixelStride(image, 0, &pixel_stride); // <-- NOT SUPPORTED FOR JPEG
```

Note, that the last 2 commands return `AMEDIA_ERROR_UNSUPPORTED` for that format.

---

Now writing on the buffer:

``` c++
  uint8_t *out = buf.data;
    for (int y = 0; y < height; y++) {
        const uint8_t *pY = pixel + width*3*y;

        for (int x = 0; x < width; x++) {
            out[x*3 + 0] = pY[x*3 + 0];
            out[x*3 + 1] = pY[x*3 + 1];
            out[x*3 + 2] = pY[x*3 + 2];
        }
        out += width*3;
    }
```

fails for some reason. The `logcat` does not output something meaningful to me - at least not readable.

**Comment by ggfan** [comment]
need to dig a little more on jpeg thing.  the write out portion, got to use stride ( not the width ) when advancing lines, correct? I would need to experiment is myself before I move on to AImage_* owner.

**Comment by skanti** [comment]
@ggfan yeah, so I found out that `getPlaneData` returns **undecoded** images with `JPEG` which is why the size varies from call to call. I think one must decode it by hand via `BitmapFactory` or so...

**Comment by ggfan** [comment]
I would think it is compressed jpeg file format, then it is saved into disk or cloud as photo.  for displaying it, got to decode it.  NDK packed MediaCodec: 
 AMediaCodec* AMediaCodec_createDecoderByType(const char *mime_type);

not sure that could be used to decode jpeg file captured from camera too.  I like to rout you to android-ndk forum, I believe camera team monitors that forum closely.  closing this now since I do not think I could add value.
