### ISSUE TITLE
native-media bug?

### ISSUE THREAD

**Issue by jenga12** [googlesamples/android-ndk#392]
I tryed "START/PAUSE NATIVE MEDIAPLAYER".
Video was played correct.
Video was paused correct.

next, I tryed "REWIND NATIVE MEDIAPLAYER".
but, Video was not rewind.
When play state is paused, Application is freezed.
When play state is stopped(playbackend), Application is not freezed. (not rewind)

Java mediaplayer all works correct.

Sample run : Android Studio 2.3.1

**Comment by ggfan** [comment]
Thank you for your reporting the bug.  Media samples are kindly of low on maintenance : I personally  not a media person.  Anyhow will try to look at it sometime, if you could dig a little deeper and add a patch, that would be great.

**Comment by ggfan** [comment]
the mentioned bug is fixed:  it is due to a deadlock:  if it is paused, it waits for the engine callback to signal the conditional variable, however in this case, engine is paused / stopped so there is no callback to happen -- hence the dead lock.  Fix is simple:  
  https://github.com/googlesamples/android-ndk/pull/430

However then we are facing more file reading issues when testing with the latest NDK.  The NDK I picked to use is NDK-R12 to replicated and tested.
