### ISSUE TITLE
Play music from external storage path

### ISSUE THREAD

**Issue by cears-jatin** [googlesamples/android-ndk#402]
Hello,
I'm using Native-Audio module for playing songs from the asset, 
how can I play music from file path?

please help me..

**Comment by ggfan** [comment]
Some samples used to play from /sdcard directory, this one might be able to help a little:
  https://github.com/googlesamples/android-ndk/tree/android-mk/native-media/jni
for the file access part of it. In order to access the file, you might have to add the run-time permission to it:  https://developer.android.com/training/permissions/requesting.html, and you would do it from Java side.

Once get file opened, you could read from it and play out, might have to do file IO thing from its own thread and have some queueing mechanism to connect to the audio interface.

hope this helps, you could also post to https://groups.google.com/forum/#!forum/android-ndk, Audio team are watching that forum very closely.
