### ISSUE TITLE
why not gnustl_static? 

### ISSUE THREAD

**Issue by yge58** [googlesamples/android-ndk#438]
https://github.com/googlesamples/android-ndk/blob/6862354e754c61aa4b9454c5834769048ebb4535/camera/basic/build.gradle#L16

My dear friends,

If I change c++_static to gnustl_static which is default [ANDROID_STL](https://developer.android.com/ndk/guides/cpp-support.html)

The error is the following, 

FAILED: image_reader.cpp:439:32: error: no member named 'to_string' in namespace 'std'

Because of openCV, I have to use gnustl_static, and this is the default on Android Studio.

I have tried to enable cppflag '-std=c++11' at two locations,
One, in 'build.gradle', I simply add in cmake { cppflags '-std=c++11' };
Two, in "CMakeLists.txt", where I did not change anything. 
https://github.com/googlesamples/android-ndk/blob/6862354e754c61aa4b9454c5834769048ebb4535/camera/basic/src/main/cpp/CMakeLists.txt#L31

So I deleted all the std::to_string from the following code,
https://github.com/googlesamples/android-ndk/blob/f5bb5e68a407fdd0b017e7ade9f8de82fb3eacb6/camera/basic/src/main/cpp/image_reader.cpp#L439

Then, compiling with gnustl_static is working.
Can anyone help me with this error? And why choose the LLVM libc++ runtime (static library) , c++_static here in this very simple native camera sample. 

Has this issue been filed before, if so, I apologise. Any help or suggestion is welcomed. 

Many thanks,

Yan

**Comment by yge58** [comment]
I am a complete android newbie, and I have another question, 
If I set std=c++11 cppflag in "build.gradle", cmake property "cppFlags", do I need to set this flag again in CMakeList.txt?

**Comment by ggfan** [comment]
thanks for reporting issues. c++_* has more functionalities than gnustl_*.  this std:to_string() thing may not be supported inside gnustl_*.   and there is no advance into gnustl_* thing anymore ( as deprecating gcc / gnustl_*, and provoking c++_* and clang instead )  The documentation needs to updated to reflect default that android is more leaning toward clang

There are noticeable difference between gnustl_* and c++_*, with latter has more functionality than before. I did not hear any plan to make gnu* things to be more compatible rather than to deprecate  them all. Yeah if you have to use gnustl_*, avoid use some advanced functionalities in stl

for c++11 flag, just add into one place is good enough. Personally I like it to be inside cmakelists.txt -- gradle is for java...
hope this helps

**Comment by yge58** [comment]
Thank you so much!

**Comment by yge58** [comment]
[this works ^^](https://stackoverflow.com/questions/22774009/android-ndk-stdto-string-support)
