### ISSUE TITLE
can not run on the latest Android Studio 3.0

### ISSUE THREAD

**Issue by Schumanzou** [googlesamples/android-ndk#453]
It can not run at the latest Android Studio3.0.
Android Studio 3.0
Build #AI-171.4408382, built on October 21, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

It crashed at LoadProgress():
void PlayScene::LoadProgress() {
    // try to load save file
    mSavedCheckpoint = 0;

    LOGD("Attempting to load: %s", mSaveFileName);
    FILE *f = fopen(mSaveFileName, "r");   **// f is NULL**
    bool hasLocalFile = false;
    if (f) {
...
}

**Comment by ggfan** [comment]
looks like this is endless tunnel sample correct?  this sample has not been upgraded to 3.0 as pointed out [here](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html). Another thing is run-time permission, you may try this to enable run-time permission with adb: 
https://developer.android.com/training/permissions/usage-notes.html#testing

please kindly update with your findings.  thanks

**Comment by Schumanzou** [comment]
Hi @ggfan 
I am a freshman on Andiord. thank you for your quick reply.
The following is my permission:
use the command: adb shell pm list permissions -d -g
group:com.google.android.gms.permission.CAR_INFORMATION
  permission:com.google.android.gms.permission.CAR_VENDOR_EXTENSION
  permission:com.google.android.gms.permission.CAR_MILEAGE
  permission:com.google.android.gms.permission.CAR_FUEL

group:android.permission-group.CONTACTS
  permission:android.permission.WRITE_CONTACTS
  permission:android.permission.GET_ACCOUNTS
  permission:android.permission.READ_CONTACTS

group:android.permission-group.PHONE
  permission:android.permission.READ_CALL_LOG
  permission:android.permission.READ_PHONE_STATE
  permission:android.permission.CALL_PHONE
  permission:android.permission.WRITE_CALL_LOG
  permission:android.permission.USE_SIP
  permission:android.permission.PROCESS_OUTGOING_CALLS
  permission:com.android.voicemail.permission.ADD_VOICEMAIL

group:android.permission-group.CALENDAR
  permission:android.permission.READ_CALENDAR
  permission:android.permission.WRITE_CALENDAR

group:android.permission-group.CAMERA
  permission:android.permission.CAMERA

group:android.permission-group.SENSORS
  permission:android.permission.BODY_SENSORS

group:android.permission-group.LOCATION
  permission:android.permission.ACCESS_FINE_LOCATION
  permission:com.google.android.gms.permission.CAR_SPEED
  permission:android.permission.ACCESS_COARSE_LOCATION

group:android.permission-group.STORAGE
  permission:android.permission.READ_EXTERNAL_STORAGE
  permission:android.permission.WRITE_EXTERNAL_STORAGE

group:android.permission-group.MICROPHONE
  permission:android.permission.RECORD_AUDIO

group:android.permission-group.SMS
  permission:android.permission.READ_SMS
  permission:android.permission.RECEIVE_WAP_PUSH
  permission:android.permission.RECEIVE_MMS
  permission:android.permission.RECEIVE_SMS
  permission:android.permission.SEND_SMS
  permission:android.permission.READ_CELL_BROADCASTS

But it still does not work.

**Comment by ggfan** [comment]
I am having a look now

**Comment by Schumanzou** [comment]
Acctually, I worked on my project(need open file by JNI) and find that the fopen is always return NULL, so I try to run the sample, and find the same issue.
thanks!

**Comment by ggfan** [comment]
the problem with this one is that: the file should is not there; but it is ok though even when there is no file there -- it returns NULL.  if it is NULL, certainly the game started from 0 level. it should not crash, am I correct?

Actually it could not save file in Android-23 and above due to run-time permission, so this game will never get to load the file for game level; hence it is alway starts from level 0.  for platform before android-23, it should be fine ( there is no run-time permission request ).  There is no storage read/write request inside AndroidManifest.xml, so the save game / load game is not intended to be functioning. Just ignore that part of the game logic at the moment then. It should not crash or anything.

**Comment by ggfan** [comment]
while we would separate the issues:  for this sample, read/write file will not work due to the lack of storage request in AndroidManifest.xml and run-time permission request. There is no null pointer access so it should not crash( it should continue to play ).  For your own project, it is the matter of how to correctly use storage access:
- for OS up to Android-22 (Android Lollipop), adding request to [AndroidManifest.xml](https://stackoverflow.com/questions/35858981/read-and-write-permission-for-storage-and-gallery-usage-for-marshmallow) is enough
- for Android-23 ( android marshmallow) and newer OS, must have run-time permission request

So in the end, your application would end up with having both storage request inside AndroidManifest.xml and run-time permission in your java code ( for Android version 23 and above ).

My understanding is that storage access has the same privilege as photos, photos means protection, so access storage need run-time permission.  The answer is in that StackOverflow link:
https://stackoverflow.com/questions/35858981/read-and-write-permission-for-storage-and-gallery-usage-for-marshmallow

**Comment by Schumanzou** [comment]
@ggfan  got it! thank you very much.
I will try it and update my finds.

**Comment by Schumanzou** [comment]
I try the Emulator with Android-22, it crashed also, please refer to the SS:
![crashed](https://user-images.githubusercontent.com/11325290/33057263-da5af526-cec4-11e7-9c2e-bcd6898d98d3.PNG)

**Comment by ggfan** [comment]
for this endless tunnel, just add this:
```java
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
right above the "<application" line inside AndroidManifest.xml
then install the endless-tunnel sample to your Android device, and on command line, do run-time permission request with
```java
adb shell pm grant com.google.sample.tunnel android.permission.WRITE_EXTERNAL_STORAGE
```
your application have the full read/write access to the storage. that should work and finally you will need add java code to do run-time permission request in a programming way ( not the command line way shown above). Once you granted write access, read access is automatically granted.

**Comment by ggfan** [comment]
Ok, could you debug to see if it is failed at the same place, and inside logcat, it would tell something like permission denied. could you confirm?  I am running with Pixel XL + Android-O MR1, it is ok.

**Comment by Schumanzou** [comment]
Thank you very much for your quick reply and patient answer.
But when I try to then Command : 
adb shell pm grant com.google.sample.tunnel android.permission.WRITE_EXTERNAL_STORAGEr
There is an issue:

![permission](https://user-images.githubusercontent.com/11325290/33058049-a0cd2c1c-cec8-11e7-9923-4a6f9081b96d.PNG)

**Comment by ggfan** [comment]
that is sad and I need to do more research.

could you try endless tunnel in this branch:
  https://github.com/googlesamples/android-ndk/tree/debug-issue-453
on your emulator and see how it goes?

**Comment by Schumanzou** [comment]
OK, thank you

**Comment by Schumanzou** [comment]
It is still has the issue. And the logcat is:
1-21 06:47:39.809 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Creating output VBO (4 vertices) and IBO (6 indices).
11-21 06:47:39.811 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Created geometry from ascii art: 4 vertices, 6 indices
11-21 06:48:06.606 3099-3165/com.google.sample.tunnel V/threaded_app: New input event: type=2
11-21 06:48:06.607 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Trying to dlopen libandroid.so
11-21 06:48:06.607 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Opened libandroid.so, looking for AMotionEvent_getAxisValue.
11-21 06:48:06.607 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: AMotionEvent_getAxisValue() address is 0xac1a2490
11-21 06:48:06.756 3099-3165/com.google.sample.tunnel V/threaded_app: New input event: type=2
11-21 06:48:06.756 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Save file name: /mnt/sdcard/com.google.example.games.tunnel.fix/tunnel.dat
11-21 06:48:06.756 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Attempting to load: /mnt/sdcard/com.google.example.games.tunnel.fix/tunnel.dat
11-21 06:48:06.756 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Save file not present.
11-21 06:48:06.756 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Checking cloud save data.
11-21 06:48:06.757 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: No cloud save available because we are not signed in.
11-21 06:48:06.759 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Final decision on starting level: 0
11-21 06:48:06.759 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Final decision on whether to use cloud: DO NOT USE CLOUD (failed)
11-21 06:48:06.759 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: SceneManager: requesting new scene 0xaf5bb300
11-21 06:48:06.759 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: SceneManager: installing scene 0xaf5bb300.
11-21 06:48:06.759 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: SceneManager: killing graphics.
11-21 06:48:06.760 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: SceneManager: starting graphics.
11-21 06:48:06.761 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: SceneManager: calling mCurScene->OnStartGraphics.
11-21 06:48:06.761 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Compiling shader.
11-21 06:48:06.761 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Shader name: OurShader
11-21 06:48:06.764 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Vertex shader compilation succeeded.
11-21 06:48:06.766 3099-3165/com.google.sample.tunnel D/EndlessTunnel:Native: Fragment shader compilation succeeded.
11-21 06:48:06.767 3099-3165/com.google.sample.tunnel E/EndlessTunnel:Native: *** Shader program link failed, 0
11-21 06:48:06.767 3099-3165/com.google.sample.tunnel E/EndlessTunnel:Native: *** GAME ABORTING.

**Comment by ggfan** [comment]
Ok, thanks. The failure is at the Linking shader, not the game level loading.

**Comment by Schumanzou** [comment]
yes, but the fopen is still return NULL.

**Comment by Schumanzou** [comment]
I test it  with Pixel XL + Android 7.0, it works good..
But loading level is still failed! fopen is still return NULL.

**Comment by Schumanzou** [comment]
ok,got it, thank you !

**Comment by ggfan** [comment]
see the file name is:
/mnt/sdcard/com.google.example.games.tunnel.fix/tunnel.dat

"adb shell" to that place, you will find it is not there in your emulator/device, you would find it is not there. the first time you run the game, it will never be there because game has not saved the level yet. Only after exiting the game, and saving game worked, then the file will be there: NEXT time when you re-run the game, it would open the file.  So it needs to be written by the game first.

You might want to set a breakpoint on PlayScene ::SaveProgress() to see how it is triggered. If it is never triggered, then there will never be a difficult level file.

[make sure your emulator has sdcard enabled too].

**Comment by Schumanzou** [comment]
got it! Thank you!
great help for me!
have a nice day!

**Comment by ggfan** [comment]
thank you for the issue.  closing this one for now. feel free to re-open
