### ISSUE TITLE
audio-echo sample doesn't work on Pixel 2 when recording audio over Bluetooth

### ISSUE THREAD

**Issue by 6bangs** [googlesamples/android-ndk#502]
Tested on a Pixel 2 running 8.1.0 (patch Feb 5 2018).

Android Studio 3.0
BuildToolsVersion 26.0.3
com.android.tools.build:gradle:3.0.1
services.gradle.org/distributions/gradle-4.1-all.zip

This appears to reproduce with all Bluetooth headsets. I modified the sample to use startBluetoothSco() before recording: https://github.com/life-beam/android-ndk/tree/audio-echo-sco

For background, this is an issue we're observing with our app that uses Nuance VoCon (an NDK library that uses OpenSL) for voice recognition. It works well on all other phones, just not the Pixel 2. Now that it reproduces here, it appears that the problem may occur at a lower level than VoCon.

**Comment by ggfan** [comment]
the sample was not tested on Bluetooth, could well be a bug in the sample. Before dive deep into it, add @donturner, @philburk if there are any gotchas for Bluetooth. 

Since this is new app, might directly use [Oboe interface.](https://github.com/google/oboe), potentially to make a bigger story out of your development.

**Comment by 6bangs** [comment]
Hmm... I don't think Oboe is a possibility for us since we depend on OpenSL transitively through VoCon. Looks cool though; we had just checked out AAudio yesterday.

Note that we're already in production; audio recording was working pretty well until the Pixel 2 was released. There was a more general bug affecting audio recording via Bluetooth, but a fix is available in 8.1. Now recording audio over Bluetooth via the Java APIs works great, but it appears that something is still missing with OpenSL (and maybe AAudio).

**Comment by atsafrir** [comment]
I added to @6bangs code BluetoothScoConnector constructer the following line audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION); and now the audio-echo sample works with bluetooth on pixel 2. @ggfan, @donturner, @philburk why does pixel 2 need a call to  audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION); while other phones don't ? This is not only a Pixel 2 issue, I have seen several android phones that behaves this way.

**Comment by ggfan** [comment]
surprising to find that:

- when it is in COMMUNICATION mode, Audio playback is FAST_PATH
- when it is NOT in COMMUNICATION mode, Audio playback is denied of FAST_PATH request

if it is not in fast path, there is no way to run this sample: the callback is so irregular that it totally breaks streams. still need to debug why it is not granted the FAST_PATH in the failure case? The asked audio buffer size 3840 (framecount) is much smaller than supported buffer size of 11544. 11544 would be minimum latency time ( my guess ), application creates buffer of 96 frames, 11544/96 = 120.25 buffers, audio echo only creates 16, it is not going to play audio like streams.

Still need more debug, @6bangs how do you come up with the workaround? just a question.

**Comment by ggfan** [comment]
Created bug b2/74176028

**Comment by 6bangs** [comment]
Thanks for the additional details; are there any docs for acquiring the FAST_PATH other than the [SO question](https://stackoverflow.com/questions/14842803/low-latency-audio-playback-on-android)? I'll dig in more later this week, but looking forward to any updates coming from your end.

@atsafrir found the workaround in this thread: https://groups.google.com/forum/#!topic/android-ndk/0zxkPODXQ14

**Comment by ggfan** [comment]
https://developer.android.com/ndk/guides/audio/audio-latency.html would be another one, that SO question would still be true (I believe).

**Comment by ggfan** [comment]
Some info: when application starts up, Bluetooth audio is at default mode:
- AUDIO_MODE_NORMAL (3)
- OutputDevice is AUDIO_DEVICE_OUT_BLUETOOTH_A2DP  ==> this does not support audio fast path.
If no audio fast path, pro audio( low latency audio) will not be enabled ( could not support it ). So you will see HUGE audio buffer:  "Client defaulted notificationFrames to 5772 for frameCount 11544".    

Once set mode to COMMUNICATION, "MEDIA is forced to use the communication routing which has higher priority [and goes to earpiece by default]". Fast mode is supported <== audio Fast mode is enabled, hence we saw smaller audio buffers and other tuned up features for audio: 
  D AudioTrack: Client defaulted notificationFrames to 96 for frameCount 384

It means that we ( applications ) will get notified after every 96 frames are consumed from playback in fast mode; while the "NORMAL" mode only notifies us for every 5772 frames ( this is too much: leave the math to you).

There is a way to detect whether we are in fast mode:

1. Request for SL_IID_ANDROIDCONFIGURATION when CreateAudioPlayer()
1. Request for SL_ANDROID_PERFORMANCE_LATENCY:
```java
    SLAndroidConfigurationItf androidCfgItf;
    result = (*playerObjectItf_)->GetInterface(playerObjectItf_, SL_IID_ANDROIDCONFIGURATION, &androidCfgItf);
    SLASSERT(result);

    SLuint32 performanceMode = SL_ANDROID_PERFORMANCE_LATENCY;
    SLuint32 len = sizeof(performanceMode);
    result = (*androidCfgItf)->SetConfiguration(androidCfgItf,
                                                SL_ANDROID_KEY_PERFORMANCE_MODE,
                                                &performanceMode,
                                                len);
    SLASSERT(result);
```
1. Check for sure PERFORMANCE_LATENCY mode is granted:
```java
    // realize the player
    result = (*playerObjectItf_)->Realize(playerObjectItf_, SL_BOOLEAN_FALSE);
    SLASSERT(result);
    performanceMode  = SL_ANDROID_PERFORMANCE_NONE;
    result = (*androidCfgItf)->GetConfiguration(androidCfgItf,
                                                SL_ANDROID_KEY_PERFORMANCE_MODE,
                                                &len, &performanceMode);
    //  SLASSERT(result);  // do not check for this return value: it is wrong, more info below.

    if (performanceMode != SL_ANDROID_PERFORMANCE_LATENCY) {
        LOGE("====Low latency mode is not supported, could not move forward");
        .... // bail out from here
    }
```

Currently there is a small bug in the framework [configuration code](https://android.googlesource.com/platform/frameworks/wilhelm/+/master/src/itf/IAndroidConfiguration.cpp#88) in that it missed a "break;" statement hence `SLAndroidConfigurationItf::GetConfiguration()` will always return UNSUPPORTED even it actually has the right values returned. So just ignore the return value from this function: it will be fixed in the future source code release. 

Sorry for the delay, hope this helps you in your future project. Basically the answer is: yeah, application must sets mode into COMMUNICATION before creating audio playback streams to get low latency playback audio.

**Comment by 6bangs** [comment]
@Vardan95 not quite sure if these are related issues; as far as I was aware, audio recording over Bluetooth was supposed to work fine on the Pixel 2 using the Java APIs.

@ggfan thanks for the write-up! This will definitely help when I can find the time to debug further. COMMUNICATION mode seems to be working in most cases, but it's not recommended by the [Android docs](https://developer.android.com/reference/android/media/AudioManager#setMode(int)):

> The audio mode encompasses audio routing AND the behavior of the telephony layer. Therefore this method should only be used by applications that replace the platform-wide management of audio settings or the main telephony application.

As far as I know, there isn't another way to update the audio mode without affecting telephony. Our customers are happy, so we're happy - but this is a heavy-handed workaround :smile:

**Comment by ggfan** [comment]
Oh, I missed some of my emails. @Vardan95, java side I am a strange, created a bug 79253330 for it, we could track it there.

@6bang, looks like I need to follow-up more on that, could be a slow efforts... but will try.  I did see other people are using it(set the communication mode). yeah, need to confirm doc and reality matches, or this is an exception...

**Comment by Demonsu** [comment]
@Vardan95 Did you solve this issue for pixel 2? I've encountered the same issue....

**Comment by Demonsu** [comment]
@ggfan Hi ggfan, any update on bug 7925330? I can't find it, could you please share a hyper link to it?

**Comment by ggfan** [comment]
yeah the bug is 79253330, it is internal bug

**Comment by Vardan95** [comment]
Hi guys, sorry for late response.
@ggfan Unfortuantely I can't find it. 
@Demonsu Nope, we didn't find any workaround for pixel 2.

**Comment by ggfan** [comment]
@Demonsu: could you file a bug from external database? I will link internal bug ( you could also do that )to it after you done, then you could have access and track it there. Not sure I could add value on Java side of framework.  Thanks

**Comment by ggfan** [comment]
I would like to close this one as java side of the things is still in my dreams. If I do get some info from the internal bug,  I will update here for sure.  Feel free to reopen it

**Comment by mahaju** [comment]
@6bangs  Hello I tried the audio-echo app in the audio-echo-sco branch linked your original post and I am trying to understand how it works. In the original audio-echo NDK program, there is a function that generates the echo and  audio delay effect on the output sound, and there is an array called liveAudio inside this function (not actually an array but a pointer to int16_t* type) which contains the latest frame of incoming audio. I can multiply the contents of this array by a number to cause an increase of output volume. Where is the corresponding array in case of audio-echo-sco?

The liveAudio pointer is actually obtained by typecasting the void *data parameter of the EngineService callback function, and the type casting is done inside a switch case under case ENGINE_SERVICE_MSG_RECORDED_AUDIO_AVAILABLE:  (value =3). This part is completely removed in audio-echo-sco and in fact the EngineService() function [audio_main.cpp] does not seem ot get called at all.

Where can I see the audio data (audio-echo-sco's' equivalent of liveAudio) in this program?
