### ISSUE TITLE
armv7a lib crash on 64 bit phone

### ISSUE THREAD

**Issue by koala99** [googlesamples/android-ndk#511]
I  compiler  static lib for android ,when used on 64 bit phone ,arc is arm64-v8a ,it crashed,
messgae like this: Fatal signal 4 (SIGILL), code 1, fault addr 0xd341e870 in tid 24564 (Thread-33), pid 24475.

**Comment by ggfan** [comment]
need more info on this: hard to pin down with that error code ( it either memory access violation, null pointer or not allow to access, my guess ); too many thing could contribute to that  error.

since you are building with gradle, build and run inside studio, see if you could use "debug" in IDE to capture where the offending code is. Or command line debugger ( it is a little tedious to set up and once it does not work, it really not work, so I kind of like avoid to go there whenever possible )
