### ISSUE TITLE
 SetPitch or SetRate

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-ndk#552]
I want to add SetPitch or SetRate to audio echo project and I can't understand how to use it.
Look at: 
https://www.khronos.org/registry/OpenSL-ES/specs/OpenSL_ES_Specification_1.1.pdf

Could you help ?

**Comment by ggfan** [comment]
that would be about playback interface, correct? you could try with this:
```
  SLInterfaceID ids[] = {SL_IID_BUFFERQUEUE, SL_IID_VOLUME, SL_IID_PITCH, SL_IID_RATEPITCH};
  SLboolean req[] = {SL_BOOLEAN_TRUE, SL_BOOLEAN_TRUE, SL_BOOLEAN_TRUE, SL_BOOLEAN_TRUE};
  result = (*slEngine)->CreateAudioPlayer(
      slEngine, &playerObjectItf_, &audioSrc, &audioSnk,
      sizeof(ids) / sizeof(ids[0]), ids, req);
  SLASSERT(result);
```
If could successfully create AudioPlayer, then it is good sign -- it is supported; then you could try:
```
  // Get Interface for PITCH
  SLPitchItf pitchItf;
  result = (*playerObjectItf_) ->GetInterface(playerObjectItf_, SL_IID_PITCH, &pitchItf);
  SLASSERT(result);
```
But the problem is that those are in game profile, not for phone; so probably will not get into Android ( they are not supported in my android phone)

**Comment by alexd555** [comment]
Hi Gerry,

I don't understand why it is not for phone ? Which phones are supported ?

Can I write ?

*pitchItf - > SetPitch(pitchItf,500)Thanks,Alex*

2018-07-31 4:06 GMT+03:00 Gerry <notifications@github.com>:

**Comment by ggfan** [comment]
need read the standard on how to retrieve the interface before you use it: It is dynamic Optional Interface. Need to get it through SL_IID_DYNAMICINTERFACEMANAGEMENT, on a Player interface. I could not get SL_IID_PITCH interface added. Referring to [documentation](https://googlesamples.github.io/android-audio-high-performance/guides/opensl_es.html), it is not in the table. Probably means not supportable on Android at all( but I need to double check ).

**Comment by alexd555** [comment]
I don't understand.

Could give me an example ?

Thanks,
Alex



2018-07-31 9:55 GMT+03:00 Gerry <notifications@github.com>:

**Comment by ggfan** [comment]
TBH, I did not understand either.  Got the answer:
- NO for SetPitch() because SI_IID_PITCH is not supported on Android
- NO for SetRate() with SK_IID_RATEPITCH for the same unsupported reason

Documentation is [here](https://developer.android.com/ndk/guides/audio/opensl/opensl-for-android#objects-and-interfaces) 
If an interface is supported, like SL_IID_PLAYBACKRATE, it could be added into the request IID list when creating AudioPlayerInterfaceObj
```
  SLInterfaceID ids[] = {SL_IID_BUFFERQUEUE, SL_IID_VOLUME, SL_IID_PLAYBACKRATE};
  SLboolean req[] = {SL_BOOLEAN_TRUE, SL_BOOLEAN_TRUE, SL_BOOLEAN_TRUE};
  result = (*slEngine)->CreateAudioPlayer(
      slEngine, &playerObjectItf_, &audioSrc, &audioSnk,
      sizeof(ids) / sizeof(ids[0]), ids, req);
  SLASSERT(result);
```

**Comment by alexd555** [comment]
Hi,

I still don't understand.
Could you point where write that SI_IID_PITCH isn't supported on Android ?
OpenSL ES  library is for android, isn't it ?

Thanks,
Alex

2018-08-01 1:04 GMT+03:00 Gerry <notifications@github.com>:

**Comment by ggfan** [comment]
this doc:
  https://developer.android.com/ndk/guides/audio/opensl/opensl-for-android#objects-and-interfaces

It is in the table of "objects and interfaces" section.

**Comment by alexd555** [comment]
But, where does write that SetPich or SI_IID_PITCH  is not supported ?

2018-08-01 20:05 GMT+03:00 Gerry <notifications@github.com>:

**Comment by ggfan** [comment]
everything supported is in there. things not in the table are NOT supported.  I did not there is this doc there: it is good one.   Audio team are serious about the Oboe, I strongly recommend you to go with Oboe instead and add your own pitich/rate in your own app.  That path is more fruitful in the long run for future.
