### ISSUE TITLE
audio-echo how can I get byte[] of recording and speaker

### ISSUE THREAD

**Issue by einsteinarbert** [googlesamples/android-ndk#621]
I am working with audio-echo sample to create karaoke app.
My issue is in this function:
`void AudioPlayer::ProcessSLCallback`
How can I save all **sample_buf *buf** to get in java code to write out to PCM file recorder?
I have been read for a long time but I didn't understand:
```
struct sample_buf {
  uint8_t* buf_;   // audio sample container (1byte music)
  uint32_t cap_;   // buffer capacity in byte
  uint32_t size_;  // audio sample size (n buf) in byte
};
```
in header file I defined: **std::vector<sample_buf*> bucket;**
Here is my customize code:
```
void AudioPlayer::ProcessSLCallback(SLAndroidSimpleBufferQueueItf bq) {
#ifdef ENABLE_LOG
  logFile_->logTime();
#endif
  std::lock_guard<std::mutex> lock(stopMutex_);

  // retrieve the finished device buf and put onto the free queue
  // so recorder could re-use it
  sample_buf *buf;
  if (!devShadowQueue_->front(&buf)) {
    /*
     * This should not happen: we got a callback,
     * but we have no buffer in deviceShadowedQueue
     * we lost buffers this way...(ERROR)
     */
    if (callback_) {
      uint32_t count;
      callback_(ctx_, ENGINE_SERVICE_MSG_RETRIEVE_DUMP_BUFS, &count);
    }
    return;
  }
  devShadowQueue_->pop();

  if (buf != &silentBuf_) {
    buf->size_ = 0;
    freeQueue_->push(buf);
    if (!playQueue_->front(&buf)) {
#ifdef ENABLE_LOG
      logFile_->log("%s", "====Warning: running out of the Audio buffers");
#endif
      return;
    }

    devShadowQueue_->push(buf);
    (*bq)->Enqueue(bq, buf->buf_, buf->size_);
    bucket.push_back(buf);
    playQueue_->pop();
    return;
  }

  if (playQueue_->size() < PLAY_KICKSTART_BUFFER_COUNT) {
    (*bq)->Enqueue(bq, buf->buf_, buf->size_);
    bucket.push_back(buf);
    devShadowQueue_->push(&silentBuf_);
    return;
  }

  assert(PLAY_KICKSTART_BUFFER_COUNT <=
         (DEVICE_SHADOW_BUFFER_QUEUE_LEN - devShadowQueue_->size()));
  for (int32_t idx = 0; idx < PLAY_KICKSTART_BUFFER_COUNT; idx++) {
    playQueue_->front(&buf);
    playQueue_->pop();
    devShadowQueue_->push(buf);
    (*bq)->Enqueue(bq, buf->buf_, buf->size_);
    bucket.push_back(buf);
  }
}
```
And in audio_main, I return that vector var:
```
JNIEXPORT jbyteArray JNICALL
Java_com_tlcreativeltd_karaokeapp_util_AudioUntil_getRecorderData(JNIEnv *env, jclass type) {
  if (engine.player_ == nullptr) {
      return nullptr;
  }
  std::vector<sample_buf*> bucket = engine.player_->getRecordData();

  LOGE("====%s bucket size %lu", __FUNCTION__, bucket.size());

  int size = static_cast<int>(bucket.size()), count = 0;
  for (int j=0; j < size; j++) {
    count += bucket[j]->size_;
  }
  jbyteArray array = env->NewByteArray(count);
  LOGE("====%s array size %d", __FUNCTION__, count);
  int seek = 0;
  for (int j=0; j < size; j++) {
    sample_buf* data = bucket[j];
    env->SetByteArrayRegion(array, seek, data->size_, reinterpret_cast<jbyte*> (data->buf_));
    seek += data->size_;
  }



  return array;
}
```
I wrote this array byte in java to file, but when open it by PCM tool, I can't hear any sound :((

**Comment by einsteinarbert** [comment]
Sorry, I post my customize code:
`void AudioPlayer::ProcessSLCallback(SLAndroidSimpleBufferQueueItf bq) {
#ifdef ENABLE_LOG
  logFile_->logTime();
#endif
  std::lock_guard<std::mutex> lock(stopMutex_);

  // retrieve the finished device buf and put onto the free queue
  // so recorder could re-use it
  sample_buf *buf;
  if (!devShadowQueue_->front(&buf)) {
    /*
     * This should not happen: we got a callback,
     * but we have no buffer in deviceShadowedQueue
     * we lost buffers this way...(ERROR)
     */
    if (callback_) {
      uint32_t count;
      callback_(ctx_, ENGINE_SERVICE_MSG_RETRIEVE_DUMP_BUFS, &count);
    }
    return;
  }
  devShadowQueue_->pop();

  if (buf != &silentBuf_) {
    buf->size_ = 0;
    freeQueue_->push(buf);
    if (!playQueue_->front(&buf)) {
#ifdef ENABLE_LOG
      logFile_->log("%s", "====Warning: running out of the Audio buffers");
#endif
      return;
    }

    devShadowQueue_->push(buf);
    (*bq)->Enqueue(bq, buf->buf_, buf->size_);
    bucket.push_back(buf);
    playQueue_->pop();
    return;
  }

  if (playQueue_->size() < PLAY_KICKSTART_BUFFER_COUNT) {
    (*bq)->Enqueue(bq, buf->buf_, buf->size_);
    bucket.push_back(buf);
    devShadowQueue_->push(&silentBuf_);
    return;
  }

  assert(PLAY_KICKSTART_BUFFER_COUNT <=
         (DEVICE_SHADOW_BUFFER_QUEUE_LEN - devShadowQueue_->size()));
  for (int32_t idx = 0; idx < PLAY_KICKSTART_BUFFER_COUNT; idx++) {
    playQueue_->front(&buf);
    playQueue_->pop();
    devShadowQueue_->push(buf);
    (*bq)->Enqueue(bq, buf->buf_, buf->size_);
    bucket.push_back(buf);
  }
}`

**Comment by einsteinarbert** [comment]
sorry, Can't I help me please !

**Comment by ggfan** [comment]
please refer to [your previous thread](https://github.com/googlesamples/android-ndk/pull/590) for some details. This is a loop on native side itself: buffers are re-used very quickly, not much chance for your java thread to use without creating contention situations. Sometimes I tried to write to a file on native side from a different thread, not tried from Java side ( audio path: recorder -> rec_queue -> writer ->playerqueue -> payer ->freequeue ->recoder)

Since audio driver / framework decides when to callback to us/app, we get no control about when the audio is ready. Then only way (to me ) is to use callback: inside audio driver's callback function, call your java side function. Pulling may not work: audio driver does not wait, and inside audio driver's callback ( it is high priority thread ), app is NOT allowed to calling into another thread's function -- there is NO native interface to create higher priority thread. There is a java side API to create audio thread ( special high priority thread ), and there is one example in oboe's sample. you might refer to that one: "fortunately" I get no experience (and probably no desire) for it, i.e., my knowledge to it is <= 0. Please check that one out too.

Again oboe is the way to go. After you finished your sample, upload to that repo so people could use it: it is very useful usage model.

**Comment by einsteinarbert** [comment]
Thanks for your answers, I resolved my issue following
https://github.com/koseonjae/Karaoke

> P/S thanks Koseonjae too.

**Comment by einsteinarbert** [comment]
Resolved by:
https://github.com/koseonjae/Karaoke
