### ISSUE TITLE
update all samples to android M

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#90]
- update permission model
- replace deprecated API

/cc @Whiteseeker

**Comment by ggfan** [comment]
a couple samples like native-audio and audio-echo would crash on Android -M (API 23) because of the run-time permission change in Android-M ( target API level 23 ).  Working on a fix and will checkin fix soon. In the mean time, you could change the targed api level to be 22 or earlier in module build.gradle:
   targetSdkVersion.apiLevel = 23   ===> targetSdkVersion.apiLevel = 22

**Comment by Whiteseeker** [comment]
By changing target api to 22, it seems that the user can still go to
settings->app->permissions and revoke any runtime permission here.
I guess it would still crash then. Plus some developer would like us to
provide the sample jni code to ask (properly) to the user for runtime
permission.

**Comment by proppy** [comment]
@Whiteseeker yes, this is being worked on in #96, #97 was just a quick workaround for the audio/video sample not to crash by default.

**Comment by ggfan** [comment]
probably only 2 are necessary due to audio recording:
   native-audio
   audio-echo

**Comment by ggfan** [comment]
created a pull: 
https://github.com/googlesamples/android-ndk/pull/206

this takes care all of the run-time permission thing.

**Comment by Zhuinden** [comment]
So how do you get external storage access from NDK? 🤔

**Comment by ggfan** [comment]
I do not think I know more than you for this :-( . internal ones are mounted to /sdcard, normal file operation would work.
