### ISSUE TITLE
Failed to attach native debugger: Device "[DEVICE_ID]" not found

### ISSUE THREAD

**Issue by WispZhan** [googlesamples/android-ndk#99]
Please help me.
I want debug my JNI code,but Android Studio show:
> Now Launching Native Debug Session
Failed to attach native debugger: Device "[DEVICE_ID]" not found
Device "[DEVICE_ID]" not found

I confirm my device has been connected, because Java Code can be debugged.

**Comment by proppy** [comment]
@WispZhan did you create a native debugging configuration as instructed by http://tools.android.com/tech-docs/android-ndk-preview?

Closing this issue since it's not really a bug report about the sample, if you have general question about Android C++ support, please use http://stackoverflow.com/ with tag [android-studio] [ndk] [c++] or http://tools.android.com/feedback
